### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by borhanreo** [manishkatyan/bbb-mp4#6]
When run the ./bbb-mp4.sh then show /var/www/bbb-mp4/webm/.webm: No such file or directory      `mp4_dir=/var/www/bigbluebutton-default/recording
webm_dir=/var/www/bbb-mp4/webm
download_dir=/var/www/bbb-mp4/download
bbb_fqdn=xyz.xyz.com
playbackFile=playback_default.html
`

**Comment by arun-hel** [comment]
Hi, @borhanreo Have you provided the meeting id for bbb-mp4.sh? Formate is `./bbb-mp4.sh MEETING_ID`.

**Comment by borhanreo** [comment]
my published meeting directory is 
`/var/bigbluebutton/published/presentation`
```
19866c98fd3ea8e5a3754c9fc2ae636a71515870-1613018265924  a93fbe89398869bbdde61ae1406188dc0ab67d7c-1613460297283
19866c98fd3ea8e5a3754c9fc2ae636a71515870-1613460884066  bf686020fd46c7ce3373d4c5dc0f65550c58882c-1613469861995
3e30f5de8720105155b44a1b37db12caa02c82f5-1613460605061
```

So i run 
`./bbb-mp4.sh bf686020fd46c7ce3373d4c5dc0f65550c58882c-1613469861995`
OR 
`./bbb-mp4.sh https://live2.classroom.com.bd/playback/presentation/2.0/playback.html?meetingId=bf686020fd46c7ce3373d4c5dc0f65550c58882c-1613469861995&t=24s`

i run using those command. showing same error
Could you tell me please correct format

**Comment by borhanreo** [comment]
YesI GOT IT, Thanks @arunkumar141997

**Comment by arun-hel** [comment]
You have to be a root user since you are running this project in `/var/www`.Then make sure you install all dependency and packages by running `./bbb-mp4-install.sh`. Then you can run `./bbb-mp4.sh bf686020fd46c7ce3373d4c5dc0f65550c58882c-1613469861995`
and it should work. One more thing, did you see any error during installation. If the installation is successful you should be able to
 `cd /var/www/bbb-mp4/webm`

**Comment by borhanreo** [comment]
I have successfully convert webm file. Is it possible to convert recording file to mp4.??

**Comment by arun-hel** [comment]
@borhanreo Yes , `./bbb-mp4.sh MEETING-ID` will convert recording into mp4.

**Comment by borhanreo** [comment]
but when i run the convert command then it's need .webm file. so i have no .webm file in my recording directory

**Comment by arun-hel** [comment]
@borhanreo please go through [how-it-works](https://github.com/manishkatyan/bbb-mp4#how-it-works) you will understand the workflow. `.webm`  will be generated by `bbb-mp4.sh`.So you don't need to worry about anything just run `./bbb-mp4.sh MEETING_ID` and your recording will be converted to mp4.

I will be closing this issue since the **No such file or directory**
has been resolved.
